packages:
  - apps/*
  - packages/*
  - packages/configs/*

catalog:
  react: ^19
  react-dom: ^19
  next: ^15
  typescript: ^5
  "@types/node": ^22
  "@types/react": ^19
  "@types/react-dom": ^19
  postcss: ^8
  tailwindcss: ^4
  "@tailwindcss/postcss": ^4
  eslint: ^9
  eslint-config-next: ^15
  "@eslint/eslintrc": ^3
  clsx: ^2
  jotai: ^2
  firebase: ^11
  lucia: ^3
  arctic: ^3
  storybook: ^8.6.4
  "@storybook/addons": ^7.6.17
  "@storybook/addon-actions": ^8.6.4
  "@storybook/addon-viewport": ^8.6.4
  "@storybook/react": ^8.6.4
  "@storybook/nextjs": ^8.6.4
  "@storybook/addon-links": ^8.6.4
  "@storybook/addon-essentials": ^8.6.4
  "@storybook/addon-onboarding": ^8.6.4
  "@storybook/addon-interactions": ^8.6.4
  "@storybook/theming": ^8.6.4